# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Deploy

on: [ workflow_dispatch ]

jobs:

  test:
    uses: ./.github/workflows/test.yml


  deploy-chrome:
    needs: [ test ]

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: pnpm/action-setup@v2
        with:
          version: 8

      - uses: actions/setup-node@v3
        with:
          cache: pnpm
          node-version: 18

      - run: pnpm install
      - run: pnpm run build
        env:
          BUILD_TARGET: chrome

      #
      #      - name: Upload to Firefox
      #        uses: yayuyokitano/firefox-addon@v0.0.6-alpha
      #        with:
      #          api_key: ${{ secrets.FIREFOX_ISSUER }}
      #          api_secret: ${{ secrets.FIREFOX_SECRET }}
      #          guid: '{}'
      #          xpi_path: dist/latest.zip


      - run: pnpm run web-ext:pack

      - name: Upload to Chrome
        uses: mnao305/chrome-extension-upload@v4.0.1
        with:
          file-path: dist-packed/latest.zip
          extension-id: 'nlacheihkljhpihchfjpmccafnipcana'
          client-id: ${{ secrets.CHROME_CLIENT_ID }}
          client-secret: ${{ secrets.CHROME_CLIENT_SECRET }}
          refresh-token: ${{ secrets.CHROME_REFRESH_TOKEN }}


