# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Deploy

on:
  workflow_dispatch:
    inputs:
      VERSION_REF:
        required: true
        type: string
        description: Set app version to deploy in semver format [0-9].[0-9].[0-9]
  release:
    types: [ created ]

jobs:

  test:
    uses: ./.github/workflows/test.yml
    with:
      VERSION_REF: ${{ inputs.VERSION_REF || github.ref }}


  deploy:
    needs: [ test ]

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: pnpm/action-setup@v2
        with:
          version: 8

      - uses: actions/setup-node@v3
        with:
          cache: pnpm
          node-version: 18

      - run: pnpm install
      - run: pnpm run build
        env:
          VERSION_REF: ${{ inputs.VERSION_REF || github.ref }}
          BUILD_TARGET: chrome

      - run: pnpm run web-ext:pack -n chrome.zip

      - name: Browser Platform Publish
        uses: PlasmoHQ/bpp@v3
        with:
          keys: ${{ secrets.BPP_KEYS }}
          file: dist-packed/chrome.zip


