name: Run tests

on: [ push, pull_request, workflow_dispatch, workflow_call ]

jobs:
  test:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: pnpm/action-setup@v2
        with:
          version: 8

      - uses: actions/setup-node@v3
        with:
          cache: pnpm
          node-version: 18

      - run: pnpm install
      - name: Install Playwright Browsers
        run: pnpm exec playwright install --with-deps

      - run: pnpm run build
        env:
          BUILD_TARGET: chrome

      - run: pnpm run test
      - uses: actions/upload-artifact@v3
        if: always()
        with:
          name: playwright-report
          path: playwright-report/
          retention-days: 30
